### ISSUE TITLE
Overlaping arcs are connected internally

### ISSUE THREAD

**Issue by Pitrsek** [horizon-eda/horizon#369]
Version: 2020-03-24
Where: Footprint editor
If you place two arcs(silkscreen layer) on top of each other, and one arc is a subset of the other -one is 180deg, the other one is smaller part:
![image](https://user-images.githubusercontent.com/16414810/78453596-0f77c900-7693-11ea-9359-aed3f7b4c08f.png)
The arcs parameters are somehow mangled together. If you move just one, the other is affected as well. Result after moving the bigger one:
![image](https://user-images.githubusercontent.com/16414810/78453635-4c43c000-7693-11ea-9c0a-02bffe2bd0bd.png)
Footprint file:
[TestPoint1.zip](https://github.com/horizon-eda/horizon/files/4431694/TestPont1.zip)

**Comment by carrotIndustries** [comment]
Again, this is more or less intended behaviour and is here to stay: Lines and arcs use junctions as their start/end/center points. Junctions may be shared among more than one line/arc to form chains. When drawing a line/arc, selecting a point that already has a junction will reuse this junction rather than creating a new one.

If you don't want this to happen, place the junction somewhere else and move it to the desired position later on.
