### ISSUE TITLE
Visual Glitch: Grid spacing weird at certain zoom steps

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#496]
Okay I have the issue that on Linux all builds have weird grid glitches.
Pictures probably say more than a thousand words:
![Screenshot_20200813_111436](https://user-images.githubusercontent.com/6620266/90116927-836b6180-dd56-11ea-9f2d-2c8861d10260.png)  

Weirdly enough there is a spacing progression from top to bottom. Zoomed out a little more:  
![Screenshot_20200813_111748](https://user-images.githubusercontent.com/6620266/90117053-a7c73e00-dd56-11ea-9ff1-a67568e5fc4e.png)  

There are "sweet spots" where this effect is less pronounced:  
![Screenshot_20200813_111822](https://user-images.githubusercontent.com/6620266/90117152-cdecde00-dd56-11ea-89f3-17cf2b010837.png)  

Without knowing the code in question: maybe this is some sort of rounding/float precision error?

**Comment by bob-u** [comment]
Does green cursor snap to the grid points as drawn?  What happens when you adjust grid settings?

**Comment by atoav** [comment]
> Does green cursor snap to the grid points as drawn? What happens when you adjust grid settings?

It seems to be related to downsampling. So it only happens if I am zoomed out enough for it to start skipping the display of (inbetween) grid points. Snapping works however (it snaps onto the original grid).

**Comment by carrotIndustries** [comment]
> Okay I have the issue that on Linux all builds have weird grid glitches.

Does this also happen at "reasonable" zoom levels or only when zooming out particularly far? Has it always been this way or did this happen since a particular commit or system upgrade?

The actual grid mark positioning is done [in the vertex shader](https://github.com/horizon-eda/horizon/blob/master/src/canvas/shaders/grid-vertex.glsl).

**Comment by bob-u** [comment]
@atoav what are your screen resolution and grid settings?

**Comment by atoav** [comment]
Okay I just tested this and it happens on Windows and Linux alike.
Grid settings are:
- `1,270 mm`
- `Square`
- zero offsets
- Fine grid modifier: `Alt`
- Grid style: `Cross`
- Grid opacity: `1.0`
- Antialiasing: `4x MSAA`

GPU is a Nvidia RTX2080M

**Comment by carrotIndustries** [comment]
Try the `grid-dbg` branch and post the lines printed on stdout that look like this: `grid 3126 mod 83`

**Comment by atoav** [comment]
For reference, that panel in the editor is 3U high (so ~129 mm):

## grid 8778 mod 100
![Screenshot_20200816_220804](https://user-images.githubusercontent.com/6620266/90343007-13d2cc00-e00d-11ea-93c8-b03958e75bcc.png)

## grid 4063 mod 68
![Screenshot_20200816_220926](https://user-images.githubusercontent.com/6620266/90343043-4977b500-e00d-11ea-94cd-b4c4f115490c.png)

## grid 7051 mod 90
![Screenshot_20200816_221048](https://user-images.githubusercontent.com/6620266/90343053-61e7cf80-e00d-11ea-8671-0d467e60bda5.png)

**Comment by carrotIndustries** [comment]
does the latest commit make a difference?

**Comment by atoav** [comment]
> does the latest commit on the grid-dbg branch make a difference?

It doesn't seem like it, still very much the same. From which direction is the grid drawn? Bottom to top?

**Comment by carrotIndustries** [comment]
> From which direction is the grid drawn? Bottom to top?

Yes, this code caclulates how many grid marks are there per line (`mod`) and how many there are in total (`n`). The grid mark is then rendered `n` times and the vertex shader https://github.com/horizon-eda/horizon/blob/master/src/canvas/shaders/grid-vertex.glsl#L11 then uses modulus and division to get the X and Y coordinates based on the instance id. My guess is that there's something going wrong with the modulus calculation since the X coordinates end up incorrectly.  https://github.com/horizon-eda/horizon/blob/6fbfb786172c339867845a6bf199ec404218bd0f/src/canvas/grid.cpp#L103-L106

**Comment by atoav** [comment]
> EDIT: the latest commit replaces the builtin mod calculation with a custom one. does this make a difference?

This does the trick yes! No more weird grid offsets at any zoom level. Not sure what is going on tho.. some type tomfoolery maybe?
