### ISSUE TITLE
Open project when pool is not installed

### ISSUE THREAD

**Issue by moritz-meier** [horizon-eda/horizon#596]
Hi,

I really like the pool structure and the new project pool / included pools workflow.

So I experimented a bit and tried to open a project while no pool was installed and expected it to just work fine, because of the project-pool. But an exception occurred: "Pool not found".

So I took a quick look into the *.hrprj project file and the *.json project-pool file and recognized that the project file is referencing an included pool (the default horizon-pool) instead of the project pool.

When I changed the pool reference in the project file and added (installed) the project-pool to horizon I was able to open the project just from the project-pool.

So I guess this a bug and the project file should reference the project-pool and not an (possibly not available) included pool?

Version: 7ff9c56e 2021-05-11 00:21:23 +0200

**Comment by carrotIndustries** [comment]
> So I guess this a bug and the project file should reference the project-pool and not an (possibly not available) included pool?

Since the introduction of the project pools, the `pool` key in the project files is ignored. It's set to the pool selected when creating the project so older versions of the app can still open it to some extent. Setting it to the project pool UUID doesn't make much sense since all project pools have the same UUID.
